subjects = ["Dragon",
"Unicorn",
"Mermaid",
"Werewolf",
"Centaur",
"Phoenix",
"Griffin",
"Sphinx",
"Basilisk",
"Vampire",
"Zombie",
"Fairy",
"Goblin",
"Orc",
"Giant",
"Elf",
"Dwarf",
"Cyclops",
"Satyr",
"Gnome",
"Witch",
"Wizard",
"Ghost",
"Kraken",
"Siren",
"Chimera",
"Hydra",
"Pegasus",
"Yeti",
"Minotaur",
"Cerberus",
"Leprechaun",
"Shapeshifter",
"Thunderbird",
"Gorgon",
"Troll",
"Imp",
"Harpy",
"Demon",
"Nymph",
"Satellite",
"Robot",
"Alien",
"Mutant",
"Android",
"Cthulhu",
"Sasquatch",
"Wendigo",
"Frost giant",
"Fire elemental",
"Sea serpent",
"Valkyrie",
"Doppelganger",
"Ogre",
"Pixie",
"Kelpie",
"Lycanthrope",
"Banshee",
"Elemental",
"Golem",
"Hobbit",
"Shade",
"Familiar",
"Jinn",
"Boggart",
"Manticore",
"Faun",
"Banshee",
"Griffon",
"Naga",
"Fenrir",
"Kitsune",
"Harpy",
"Cockatrice",
"Thunderbird",
"Incubus",
"Wraith",
"Mummy",
"Satyr",
"Lamia",
"Chupacabra",
"Gryphon",
"Gelatinous cube",
"Necromancer",
"Shapeshifter",
"Elemental",
"Banshee",
"Nymph",
"Dryad",
"Orc",
"Goblin",
"Witch",
"Frost giant",
"Gargoyle",
"Hippogriff",
"Cyclops",
"Djinn",
"Lich",
"Zombie",
"Doctor",
"Chef",
"Teacher",
"Athlete",
"Artist",
"Engineer",
"Scientist",
"Firefighter",
"Police officer",
"Singer",
"Dancer",
"Photographer",
"Writer",
"Pilot",
"Explorer",
"Carpenter",
"Farmer",
"Waiter/Waitress",
"Designer",
"Veterinarian",
"Baker",
"Mechanic",
"Surgeon",
"Lawyer",
"Musician",
"Architect",
"Fisherman",
"Soldier",
"Actor/Actress",
"Reporter",
"Gardener",
"Nurse",
"Psychologist",
"Fashion designer",
"Painter",
"Sculptor",
"DJ",
"Barista",
"Biologist",
"Translator",
"Electrician",
"Plumber",
"Entrepreneur",
"Magician",
"Surfer",
"Lifeguard",
"Graphic designer",
"Flight attendant",
"Fitness instructor",
"Librarian"]


objects = ["bicycle", "smartphone", "coffee mug", "guitar", "bookshelf", "camera", "backpack", "umbrella", "tennis racquet", "sunglasses", "wristwatch", "headphones", "laptop", "painting", "drone", "telescope", "fishing rod", "chess set", "blender", "bicycle helmet", "alarm clock", "microwave oven", "hammock", "yoga mat", "toolbox", "pencil", "wallet", "water bottle", "soccer ball", "hiking boots", "game console", "binoculars", "snowboard", "easel", "candles", "sunhat", "portable charger", "chessboard", "telescope", "binoculars", "e-reader", "drone", "camping tent", "barbecue grill", "paintbrush", "thermos", "skateboard", "record player", "cello", "flower vase", "sewing machine", "musical keyboard", "steamer", "picnic basket", "dumbbells", "yoga block", "blender", "toaster", "hair dryer", "paper shredder", "electric fan", "chess clock", "GPS navigator", "water filter", "jump rope", "tennis ball", "dartboard", "projector", "guitar pick", "sketchbook", "suitcase", "telescope", "waffle maker", "stand mixer", "sewing kit", "safety pins", "fishing net", "paint roller", "bicycle pump", "ping pong paddle", "chess pieces", "tea set", "easel", "corkscrew", "curling iron", "treadmill", "watering can", "ski goggles", "portable speaker", "binoculars", "coffee grinder", "ironing board", "game controller", "dartboard", "guitar strap", "hiking backpack", "oven mitts", "camping stove", "kettlebell", "resistance bands", "roller skates", "sewing thread", "paint palette", "fishing tackle box", "folding chair", "snorkel mask", "bread maker", "electric toothbrush", "hair straightener", "blender bottle", "paddleboard", "projector screen", "camera tripod", "telescope", "compass", "sleeping bag", "rice cooker", "scissors", "sewing needle", "paint roller", "backpacking tent", "fishing reel", "golf clubs", "bicycle lock", "ping pong table", "chess timer", "tea infuser", "easel stand", "ice skates", "whisk", "game dice", "guitar stand", "camping hammock", "handheld vacuum", "curling wand", "kettle", "resistance bands", "volleyball", "paddle ball set", "kayak", "projector mount", "camera lens", "compass"]


environments = ["Lush Rainforest",
"Arctic Tundra",
"Barren Desert",
"Misty Marsh",
"Snowy Mountains",
"Sandy Beach",
"Rocky Canyon",
"Majestic Waterfall",
"Mysterious Cave",
"Endless Ocean",
"Enchanted Forest",
"Scorching Desert",
"Whispering Woodlands",
"Gloomy Swamp",
"Frozen Wasteland",
"Secluded Island",
"Bustling Cityscape",
"Subterranean Cavern",
"Rolling Hills",
"Ethereal Clouds",
"Underwater Coral Reef",
"Urban Jungle",
"Serenity Garden",
"Crystalline Iceberg",
"Ancient Ruins",
"Rustic Countryside",
"Volcanic Crater",
"Celestial Sky",
"Sublime Cliffs",
"Picturesque Meadow",
"Lost Temple",
"Rumbling Volcano",
"Mystical Wasteland",
"Bustling Marketplace",
"Peaceful Oasis",
"Industrial Factory",
"Whirling Dust Storm",
"Enigmatic Labyrinth",
"Futuristic Megacity",
"Icy Glacier",
"Ancient Forest",
"Ethereal Seaside",
"Hidden Grotto",
"Serene Pasture",
"Cosmic Nebula",
"Sunlit Savanna",
"Urban Rooftops",
"Whispering Canyon",
"Magical Garden",
"Underground Dungeon",
"Roaring Water Rapids",
"Peaceful Countryside",
"Misty Highlands",
"Surreal Dreamscape",
"Crystal Clear Lake",
"Abandoned Factory",
"Steaming Hot Springs",
"Windswept Dunes",
"Enchanted Castle",
"Electric Cityscape",
"Charming Vineyard",
"Sun-drenched Coastline",
"Timeless Library",
"Frozen Arctic",
"Ethereal Moonlit Glade",
"Tropical Paradise",
"Desolate Wasteland",
"Peaceful Zen Garden",
"Shadowy Dungeon",
"Vibrant Coral Reef",
"Enchanting Waterfall",
"Majestic Mountain Range",
"Mysterious Shipwreck",
"Flickering Fire Swamp",
"Futuristic Space Station",
"Magical Floating Islands",
"Serenading Riverbank",
"Mossy Enchanted Grove",
"Glowing Bioluminescent Cave",
"Rugged Wild West",
"Soothing Hot Springs",
"Eternal Ice Kingdom",
"Bustling Night Market",
"Ancient Temple",
"Twilight City",
"Mystical Misty Moors",
"Sun-kissed Vineyard",
"Futuristic Cyberpunk City",
"Peaceful Mountain Retreat",
"Emerald Green Forest",
"Whimsical Underwater Garden",
"Hidden Underground City",
"Haunted Cemetery",
"Sandy"]



famous_artists = ["Leonardo da Vinci",
"Pablo Picasso",
"Vincent van Gogh",
"Michelangelo",
"Claude Monet",
"Andy Warhol",
"Salvador Dalí",
"Rembrandt",
"Frida Kahlo",
"Georgia O'Keeffe",
"Johannes Vermeer",
"Edvard Munch",
"Jackson Pollock",
"Gustav Klimt",
"Henri Matisse",
"Auguste Rodin",
"Marc Chagall",
"Edgar Degas",
"Diego Rivera",
"Mark Rothko",
"Caravaggio",
"Roy Lichtenstein",
"Paul Cézanne",
"Rene Magritte",
"Joan Miró",
"Francisco Goya",
"Kazimir Malevich",
"Henri Cartier-Bresson",
"Ansel Adams",
"Edward Hopper",
"Banksy",
"Yayoi Kusama",
"Keith Haring",
"Ai Weiwei",
"Cindy Sherman",
"Marcel Duchamp",
"Grant Wood",
"Willem de Kooning",
"Piet Mondrian",
"Hokusai",
"Peter Paul Rubens",
"Man Ray",
"Giotto di Bondone",
"Diego Velázquez",
"Jean-Michel Basquiat",
"Faith Ringgold",
"Louise Bourgeois",
"Helen Frankenthaler",
"Fernando Botero",
"Jeff Koons",
"Mary Cassatt",
"Alberto Giacometti",
"Artemisia Gentileschi",
"Damien Hirst",
"Barbara Hepworth",
"Frida Escobedo",
"Kara Walker",
"Bridget Riley",
"Ai Xuan",
"Thomas Hart Benton",
"Nam June Paik",
"Eugène Delacroix",
"Frank Gehry",
"George Seurat",
"Hans Holbein the Younger",
"Takashi Murakami",
"El Greco",
"Norman Rockwell",
"Camille Claudel",
"Paul Gauguin",
"Edward Weston",
"Jenny Holzer",
"Louise Nevelson",
"Gerhard Richter",
"James Turrell"]

locations = ["Mountains",
"Beach",
"City",
"Forest",
"Desert",
"Island",
"Lake",
"Countryside",
"Jungle",
"River",
"Valley",
"Waterfall",
"Cave",
"Glacier",
"Volcano",
"Canyon",
"Wetland",
"Prairie",
"Plateau",
"Archipelago",
"Peninsula",
"Tundra",
"Oasis",
"Estuary",
"Fjord",
"Dune",
"Highlands",
"Lowlands",
"Gorge",
"Delta",
"Meadow",
"Cliff",
"Islet",
"Steppe",
"Badlands",
"Atoll",
"Mangrove",
"Moor",
"Reef",
"Crater",
"Savannah",
"Wetlands",
"Karst",
"Coral Reef",
"Crag",
"Butte",
"Lagoon",
"Foothills",
"Salt Flat",
"Dell",
"Sand Dunes",
"Tide Pool",
"Moraine",
"Cinder Cone",
"Slope",
"Bog",
"Firth",
"Seashore",
"Bight",
"Dell",
"Estuary",
"Heath",
"Promontory",
"Ravine",
"Watershed",
"Tableland",
"Thicket",
"Wadi",
"Reservoir",
"Bassin",
"Corrie",
"Escarpment",
"Cove",
"Headland",
"Hillside",
"Isthmus",
"Knoll",
"Lowland",
"Outcrop",
"Overhang",
"Piedmont",
"Polder",
"Ridge",
"Sound",
"Strait",
"Tarn",
"Terrace",
"Waterway",
"Wilderness",
"Woods",
"Park",
"Plains",
"Cemetery",
"Village",
"Harbor",
"Quarry",
"Ranch",
"Farm",
"Campground",
"Mansion"]

stylings = ["Abstract Expressionism",
"Impressionism",
"Cubism",
"Surrealism",
"Pop Art",
"Minimalism",
"Realism",
"Pointillism",
"Fauvism",
"Post-Impressionism",
"Op Art",
"Dadaism",
"Art Nouveau",
"Rococo",
"Gothic",
"Baroque",
"Renaissance",
"Neo-Impressionism",
"Symbolism",
"Photorealism",
"Constructivism",
"Suprematism",
"Action Painting",
"Color Field Painting",
"Tonalism",
"Precisionism",
"Social Realism",
"Sgraffito",
"Trompe-l'oeil",
"Art Deco",
"Graffiti",
"Digital Art",
"Kinetic Art",
"Land Art",
"Street Art",
"Sculpture",
"Installation Art",
"Environmental Art",
"Collage",
"Assemblage",
"Stencil Art",
"Etching",
"Engraving",
"Woodcut",
"Monotype",
"Screenprinting",
"Lithography",
"Copperplate",
"Mosaic",
"Pottery",
"Ceramics",
"Glassblowing",
"Stained Glass",
"Textile Art",
"Quilting",
"Embroidery",
"Macramé",
"Origami",
"Calligraphy",
"Ink Wash Painting",
"Sumi-e",
"Chiaroscuro",
"Tenebrism",
"Photography",
"Pinhole Photography",
"Polaroid Art",
"Photo Manipulation",
"Mixed Media",
"Encaustic Painting",
"Gyotaku",
"Printmaking",
"Batik",
"Tapestry",
"Performance Art",
"Body Art",
"Happening",
"Video Art",
"Virtual Reality Art",
"Generative Art",
"Neon Art",
"Steampunk",
"Naïve Art",
"Outsider Art",
"Primitivism",
"Digital Collage",
"Bio-Art",
"Interactive Art",
"Conceptual Art",
"Neo-Conceptualism",
"Bio-Design",
"Data Visualization",
"Projection Mapping",
"Light Art",
"Sound Art",
"Manga",
"Anime",
"Calligraffiti",
"Pixel Art",
"Steampunk",
"Augmented Reality Art"]


prepositions = ["About",
"Above",
"Across",
"After",
"Against",
"Along",
"Amid",
"Among",
"Around",
"As",
"At",
"Before",
"Behind",
"Below",
"Beneath",
"Beside",
"Between",
"Beyond",
"But",
"By",
"Concerning",
"Considering",
"Despite",
"Down",
"During",
"Except",
"For",
"From",
"In",
"Inside",
"Into",
"Like",
"Near",
"Of",
"Off",
"On",
"Onto",
"Out",
"Outside",
"Over",
"Past",
"Regarding",
"Round",
"Since",
"Through",
"Throughout",
"To",
"Toward",
"Under",
"Underneath",
"Until",
"Unto",
"Up",
"Upon",
"With",
"Within",
"Without",
"According to",
"Ahead of",
"Apart from",
"As for",
"As of",
"As per",
"As to",
"Aside from",
"Because of",
"Close to",
"Contrary to",
"Due to",
"Except for",
"In addition to",
"In front of",
"In spite of",
"Instead of",
"Next to",
"On account of",
"On behalf of",
"Out of",
"Owing to",
"Prior to",
"Regardless of",
"Subsequent to",
"Together with",
"Up to",
"As far as",
"As well as",
"In between",
"In line with",
"In place of",
"In regard to",
"In relation to",
"In terms of",
"In the midst of",
"On top of",
"Out from",
"Outside of",
"Thanks to",
"Up until",
"With regard to",
"With respect to"]



adjectives = ["Energetic",
"Brilliant",
"Spectacular",
"Vibrant",
"Exquisite",
"Gorgeous",
"Captivating",
"Enchanting",
"Majestic",
"Radiant",
"Fascinating",
"Charming",
"Graceful",
"Serene",
"Stunning",
"Breathtaking",
"Mesmerizing",
"Delightful",
"Wonderful",
"Magical",
"Intriguing",
"Harmonious",
"Dreamy",
"Awe-inspiring",
"Dazzling",
"Enthralling",
"Alluring",
"Spellbinding",
"Splendid",
"Glamorous",
"Elegant",
"Mysterious",
"Luminous",
"Ravishing",
"Fantastic",
"Surreal",
"Epic",
"Unforgettable",
"Delicate",
"Whimsical",
"Thrilling",
"Dynamic",
"Sparkling",
"Adventurous",
"Soothing",
"Transcendent",
"Hypnotic",
"Mellow",
"Bewitching",
"Resplendent",
"Jaw-dropping",
"Phenomenal",
"Impressive",
"Bursting",
"Colorful",
"Lively",
"Refreshing",
"Rhythmic",
"Enlivening",
"Inspiring",
"Quirky",
"Sensational",
"Playful",
"Calm",
"Intricate",
"Bold",
"Magical",
"Eclectic",
"Dynamic",
"Electrifying",
"Incredible",
"Imaginative",
"Empowering",
"Uplifting",
"Melodic",
"Satisfying",
"Exhilarating",
"Whispering",
"Celestial",
"Intense",
"Provocative",
"Seductive",
"Sonic",
"Honest",
"Powerful",
"Inventive",
"Ethereal",
"Effervescent",
"Immersive",
"Kinetic",
"Mystical",
"Bouncy",
"Melancholic",
"Tranquil",
"Explosive",
"Enigmatic",
"Majestic",
"Grand",
"Spirited",
"Exhilarating"]



verbs = ["Running",
"Jumping",
"Swimming",
"Singing",
"Dancing",
"Reading",
"Writing",
"Drawing",
"Painting",
"Playing",
"Eating",
"Drinking",
"Sleeping",
"Walking",
"Talking",
"Listening",
"Laughing",
"Crying",
"Thinking",
"Imagining",
"Creating",
"Building",
"Exploring",
"Solving",
"Teaching",
"Learning",
"Cooking",
"Baking",
"Planting",
"Growing",
"Harvesting",
"Climbing",
"Balancing",
"Flying",
"Driving",
"Traveling",
"Studying",
"Exercising",
"Competing",
"Winning",
"Losing",
"Helping",
"Supporting",
"Caring",
"Loving",
"Hugging",
"Kissing",
"Fighting",
"Protecting",
"Rescuing",
"Guiding",
"Discovering",
"Admiring",
"Appreciating",
"Believing",
"Conquering",
"Challenging",
"Encouraging",
"Motivating",
"Inspiring",
"Relaxing",
"Cleaning",
"Organizing",
"Fixing",
"Decorating",
"Capturing",
"Celebrating",
"Performing",
"Completing",
"Reflecting",
"Pondering",
"Forgiving",
"Apologizing",
"Changing",
"Adapting",
"Transforming",
"Inventing",
"Improving",
"Sharing",
"Inviting",
"Connecting",
"Collaborating",
"Succeeding",
"Failing",
"Overcoming",
"Capturing",
"Photographing",
"Designing",
"Composing",
"Crafting",
"Expiring",
"Traveling",
"Conquering",
"Questioning",
"Cherishing",
"Enlightening",
"Reminiscing",
"Celebrating",
"Experimenting",
"Reviving"]




adverbs = ["Accidentally",
"Actually",
"Almost",
"Always",
"Anxiously",
"Badly",
"Briskly",
"Carefully",
"Cheerfully",
"Clearly",
"Closely",
"Completely",
"Constantly",
"Courageously",
"Crazily",
"Curiously",
"Deeply",
"Deliberately",
"Desperately",
"Diligently",
"Eagerly",
"Easily",
"Efficiently",
"Energetically",
"Enthusiastically",
"Eventually",
"Exactly",
"Exclusively",
"Extremely",
"Firmly",
"Frequently",
"Generously",
"Gently",
"Gladly",
"Gracefully",
"Gratefully",
"Happily",
"Hardly",
"Hastily",
"Honestly",
"Hopefully",
"Immediately",
"Impartially",
"Intensely",
"Ironically",
"Joyfully",
"Kindly",
"Lazily",
"Lightly",
"Loudly",
"Lovingly",
"Mentally",
"Meticulously",
"Miserably",
"Naturally",
"Nearly",
"Nervously",
"Nicely",
"Obviously",
"Occasionally",
"Often",
"Only",
"Perfectly",
"Politely",
"Poorly",
"Powerfully",
"Promptly",
"Quietly",
"Quickly",
"Rarely",
"Rather",
"Really",
"Recently",
"Reluctantly",
"Repetitively",
"Rudely",
"Safely",
"Seldom",
"Seriously",
"Silently",
"Simply",
"Sincerely",
"Slowly",
"Smoothly",
"Solemnly",
"Specially",
"Steadily",
"Sternly",
"Suddenly",
"Surely",
"Tensely",
"Terribly",
"Thankfully",
"Tightly",
"Tremendously",
"Truly",
"Typically",
"Uneasily",
"Usually",
"Warmly"]