# Generated by Django 4.2.2 on 2023-07-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
