# Generated by Django 4.2.3 on 2023-07-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageGeneration", "0002_rename_prompt_prompts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompts",
            old_name="text",
            new_name="text_field",
        ),
    ]
