# Generated by Django 4.2.3 on 2023-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageGeneration", "0003_rename_text_prompts_text_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field", models.TextField()),
                ("datetime_field", models.DateTimeField(auto_now_add=True)),
                ("image_field", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.RenameModel(
            old_name="Prompts",
            new_name="Prompt",
        ),
    ]
