# Generated by Django 4.2.3 on 2023-07-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageGeneration", "0006_alter_image_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
    ]
