# Generated by Django 4.2 on 2023-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageGeneration', '0007_remove_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='id',
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
