# Generated by Django 4.2 on 2023-07-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageGeneration', '0009_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
